#!/usr/bin/env bash
# prints the message infinity and beyond

echo $$ > /var/run/myscript.pid

close()
{
  echo "$1"
  return
}

delete_file()
{
  if [ -e "/var/run/my.pid" ]
  then
    rm /var/run/my.pid
  fi
}


# Handle SIGTERM
trap "close 'I hate the kill command' && delete_file && exit" SIGTERM

# Handle SIGINT
trap "close 'Y U no love me?!' && exit"  SIGINT

# Handle SIGQUIT
trap "delete_file && exit" SIGQUIT

# print the message forever
while true;
do
  echo "To infinity and beyond";
  sleep 2
done
